version: "2.3"

services:
  app:
    image: interledgerjs/rafiki
    depends_on:
      - migration
      - db
    restart: always
    env_file:
      - ./rafiki.env
    networks:
      - web
    ports: 
      - "7780:7780"
      - "8843:8443"
      - "7768:7768"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.ilp.frontend.rule=Host:<HOSTNAME>;Path:/ilp"
      - "traefik.ilp.protocol=http"
      - "traefik.ilp.port=8443"
      - "traefik.btp.frontend.rule=Host:<HOSTNAME>;Path:/btp"
      - "traefik.btp.protocol=http"
      - "traefik.btp.port=7768"
      - "traefik.admin.frontend.rule=Host:<HOSTNAME>;PathPrefixStrip:/admin/"
      - "traefik.admin.protocol=http"
      - "traefik.admin.port=7780"

  migration:
    image: interledgerjs/rafiki
    depends_on:
      - db
    networks:
      - web
    env_file:
      - ./rafiki.env
    entrypoint: ["./wait-for-it.sh", "db:3306", "--", "node", "./build/src/migrate.js"]
    restart: on-failure

  db:
    image: mysql:5.7
    restart: always
    networks:
      - web
    ports: 
      - "3306:3306"
    env_file:
      - ./rafiki.env

networks:
  web:
    external: true
