apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rafiki.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rafiki.name" . }}
    helm.sh/chart: {{ include "rafiki.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rafiki.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rafiki.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CONNECTOR_ILP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{.Chart.Name}}-configmap
                  key: CONNECTOR_ILP_ADDRESS
            - name: CONNECTOR_HTTP_SERVER_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{.Chart.Name}}-configmap
                  key: CONNECTOR_HTTP_SERVER_PATH
            - name: CONNECTOR_DATABASE_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: {{.Chart.Name}}-configmap
                  key: CONNECTOR_DATABASE_CONNECTION_STRING
            - name: CONNECTOR_AUTH_PROVIDER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{.Chart.Name}}-configmap
                  key: CONNECTOR_AUTH_PROVIDER_URL
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{.Chart.Name}}-configmap
                  key: LOG_LEVEL
            - name: ADMIN_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{.Chart.Name}}-secret
                  key: ADMIN_AUTH_TOKEN
          {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
