apiVersion: v1
kind: Service
metadata:
  name: {{ include "rafiki.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rafiki.name" . }}
    helm.sh/chart: {{ include "rafiki.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $port := .Values.service.ports }}
    - port: {{ $port.externalPort }}
      targetPort: {{ $port.internalPort }}
      protocol: TCP
      name: {{ $port.name }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "rafiki.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
