name: publish

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Use yarn
      uses: Borales/actions-yarn@master
    - name: Authenticate with registry
      run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > $GITHUB_WORKSPACE/.npmrc
      shell: bash
      env:
        NPM_AUTH_TOKEN: ${{secrets.npm_token}}
    - name: install 
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: lint
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: lint
    - name: build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
    - name: test
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: test:ci
    - name: upload code coverage and publish
      run: |
        yarn codecov
        yarn release:publish 
      env:
        CI: true
        CODECOV_TOKEN: ${{secrets.codecov_token}}